// src/app/layout.jsx
'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Cookies from 'js-cookie';
import JWTverify from '../JWTverify.js';
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./header.jsx";
import Footer from "./footer.jsx";
//import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

//export const metadata = {
 // title: "Create Next App",
 // description: "Generated by create next app",
//};

export default function RootLayout({ children }) {
  const router = useRouter();
 

  return (
    <html lang="en" className="">
      <body className={`${inter.className} grid grid-rows-layout min-h-screen`}>
        
          <Header /> {/* Include your header component */}
          <div className="overflow-auto">
            {children}
          </div>
          <Footer /> {/* Include your footer component */}
        
      </body>
    </html>
  );
}
